# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c201b5d182af36072cfe2efbe1637e8d4c355f3f1580a4dd718d49ef1144cbc83eceaf60d219f18c510fc752d865d2d80b1512ed049ce49fbf842418ab8c7d25

test:
  secret_key_base: 32b6f12d599910061ecce81ec56373ef700dc2c8005d632c0ac10bbdd2bb8e0f4efbabb7c5e19f1c30369d9519af1292bd22e3b023e86b53e2fa972b446bdc6a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
